### ISSUE TITLE
分享我在docker上的compose设置

### ISSUE THREAD

**Issue by tyutzj** [any-listen/any-listen#10]
```dockerfile
services:
  anylisten:
    image: lyswhut/any-listen-web-server:main
    restart: always
    container_name: anylisten
    volumes:
      - ./music:/music
      - ./data:/server/data
    ports:
      - 9500:9500
    environment:
      - LOGIN_PWD=123456a
      - ALLOW_PUBLIC_DIR=/music
```

**Comment by disburden** [comment]
能用
谢谢分享,希望这个web版早日实现lx的精华功能

**Comment by white8night** [comment]
```yaml
name: 'any_listen'
services:
    web:
        image: 'lyswhut/any-listen-web-server:latest'
        container_name: any_listen
        ports:
            - '9500:9500'
        volumes:
            - './data:/server/data'
            - './music:/music'
```
